import { useState } from "react";

export default function Contact() {
  const [form, setForm] = useState({ name:"", email:"", subject:"", message:"" });
  const [sent, setSent] = useState(false);

  const handle = (e) => setForm({...form, [e.target.name]: e.target.value});

  const submit = (e) => {
    e.preventDefault();
    window.location.href = `mailto:support@foodcontinent.com?subject=${encodeURIComponent(form.subject)}&body=${encodeURIComponent(`Name: ${form.name}\nEmail: ${form.email}\n\n${form.message}`)}`;
    setSent(true);
  };

  const inputStyle = { width:"100%", background:"rgba(255,255,255,0.06)", border:"1px solid rgba(255,255,255,0.12)", borderRadius:12, padding:"12px 16px", color:"#fff", fontSize:14, outline:"none", boxSizing:"border-box", marginBottom:12 };

  return (
    <div style={{ minHeight:"100vh", background:"#0B0B0F", fontFamily:"'Inter',system-ui,sans-serif", color:"#fff", padding:"40px 20px" }}>
      <div style={{ maxWidth:600, margin:"0 auto" }}>
        <a href="/" style={{ color:"#FF7A00", fontSize:13, textDecoration:"none", display:"inline-block", marginBottom:24 }}>← Back to Food Continent</a>

        <h1 style={{ fontSize:32, fontWeight:900, marginBottom:8, background:"linear-gradient(90deg,#FF7A00,#FFC857)", WebkitBackgroundClip:"text", WebkitTextFillColor:"transparent" }}>Contact Us</h1>
        <p style={{ color:"rgba(255,255,255,0.4)", fontSize:14, marginBottom:40, lineHeight:1.6 }}>Have a question, feedback, or want to partner with us? We'd love to hear from you.</p>

        {/* Contact Info Cards */}
        <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:12, marginBottom:32 }}>
          {[
            { icon:"📧", title:"Email", value:"support@foodcontinent.com", link:"mailto:support@foodcontinent.com" },
            { icon:"🌐", title:"Website", value:"www.foodcontinent.com", link:"https://www.foodcontinent.com" },
          ].map((item,i) => (
            <a key={i} href={item.link} style={{ background:"rgba(255,255,255,0.04)", borderRadius:14, padding:20, border:"1px solid rgba(255,255,255,0.06)", textDecoration:"none", display:"block" }}>
              <div style={{ fontSize:28, marginBottom:8 }}>{item.icon}</div>
              <p style={{ fontSize:11, color:"rgba(255,122,0,0.8)", fontWeight:700, textTransform:"uppercase", letterSpacing:1, marginBottom:4 }}>{item.title}</p>
              <p style={{ fontSize:13, color:"rgba(255,255,255,0.6)" }}>{item.value}</p>
            </a>
          ))}
        </div>

        {/* Contact Form */}
        <div style={{ background:"rgba(255,255,255,0.04)", borderRadius:20, padding:28, border:"1px solid rgba(255,255,255,0.06)" }}>
          <h2 style={{ fontSize:18, fontWeight:700, color:"#fff", marginBottom:20 }}>Send us a message</h2>
          {sent ? (
            <div style={{ textAlign:"center", padding:32 }}>
              <div style={{ fontSize:48, marginBottom:12 }}>✅</div>
              <p style={{ fontSize:16, fontWeight:700, color:"#34d399", marginBottom:8 }}>Message sent!</p>
              <p style={{ fontSize:13, color:"rgba(255,255,255,0.4)" }}>Your email client should have opened. We'll get back to you within 24 hours.</p>
            </div>
          ) : (
            <form onSubmit={submit}>
              <input name="name" value={form.name} onChange={handle} placeholder="Your name" required style={inputStyle} />
              <input name="email" value={form.email} onChange={handle} placeholder="Your email" type="email" required style={inputStyle} />
              <input name="subject" value={form.subject} onChange={handle} placeholder="Subject" required style={inputStyle} />
              <textarea name="message" value={form.message} onChange={handle} placeholder="Your message..." required rows={5} style={{...inputStyle, resize:"vertical", marginBottom:20}} />
              <button type="submit" style={{ width:"100%", padding:"14px", borderRadius:12, border:"none", background:"linear-gradient(135deg,#FF7A00,#FFC857)", color:"#0B0B0F", fontSize:14, fontWeight:800, cursor:"pointer" }}>
                Send Message →
              </button>
            </form>
          )}
        </div>

        {/* FAQ */}
        <div style={{ marginTop:32 }}>
          <h2 style={{ fontSize:20, fontWeight:700, color:"#fff", marginBottom:16 }}>Frequently Asked Questions</h2>
          {[
            { q:"Is Food Continent free to use?", a:"Yes! Food Continent is completely free to use. We display ads to support the service." },
            { q:"How are recipes generated?", a:"Our recipes are generated by Claude, an advanced AI developed by Anthropic. Each recipe is unique and tailored to your preferences." },
            { q:"How do the nearby restaurants work?", a:"We use Google Places API to find real restaurants near your GPS location. You must allow location access for this feature to work." },
            { q:"Is my data private?", a:"Yes. We don't require account creation. Your preferences are stored locally on your device and never sent to our servers. Read our Privacy Policy for full details." },
            { q:"Can I suggest a feature?", a:"Absolutely! Email us at support@foodcontinent.com with your suggestions. We read every email." },
          ].map((faq, i) => (
            <div key={i} style={{ background:"rgba(255,255,255,0.03)", borderRadius:12, padding:"16px 20px", marginBottom:10, border:"1px solid rgba(255,255,255,0.05)" }}>
              <p style={{ fontSize:14, fontWeight:700, color:"#fff", marginBottom:6 }}>Q: {faq.q}</p>
              <p style={{ fontSize:13, color:"rgba(255,255,255,0.5)", lineHeight:1.6 }}>A: {faq.a}</p>
            </div>
          ))}
        </div>

        <div style={{ textAlign:"center", marginTop:32, display:"flex", justifyContent:"center", gap:24 }}>
          <a href="/" style={{ color:"rgba(255,255,255,0.3)", fontSize:12, textDecoration:"none" }}>Home</a>
          <a href="/about" style={{ color:"rgba(255,255,255,0.3)", fontSize:12, textDecoration:"none" }}>About</a>
          <a href="/privacy" style={{ color:"rgba(255,255,255,0.3)", fontSize:12, textDecoration:"none" }}>Privacy Policy</a>
        </div>
      </div>
    </div>
  );
}
