export default function Terms() {
  return (
    <div style={{ minHeight:"100vh", background:"#0B0B0F", fontFamily:"'Inter',system-ui,sans-serif", color:"#fff", padding:"40px 20px" }}>
      <div style={{ maxWidth:700, margin:"0 auto" }}>
        <a href="/" style={{ color:"#FF7A00", fontSize:13, textDecoration:"none", display:"inline-block", marginBottom:24 }}>← Back to Food Continent</a>
        <h1 style={{ fontSize:32, fontWeight:900, marginBottom:8, background:"linear-gradient(90deg,#FF7A00,#FFC857)", WebkitBackgroundClip:"text", WebkitTextFillColor:"transparent" }}>Terms of Service</h1>
        <p style={{ color:"rgba(255,255,255,0.4)", fontSize:13, marginBottom:40 }}>Last updated: June 27, 2026</p>

        {[
          { title:"1. Acceptance of Terms", body:`By accessing and using Food Continent at foodcontinent.com ("the Service"), you accept and agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our Service.` },
          { title:"2. Description of Service", body:`Food Continent is an AI-powered food discovery platform that helps users find recipes and nearby restaurants. The Service is provided "as is" and we reserve the right to modify, suspend, or discontinue it at any time.` },
          { title:"3. Use of the Service", body:`You agree to use the Service only for lawful purposes. You must not:\n\n• Use the Service in any way that violates applicable laws or regulations\n• Attempt to gain unauthorized access to any part of the Service\n• Use automated tools to scrape or collect data from the Service\n• Reproduce, duplicate, or copy content from the Service for commercial purposes without permission` },
          { title:"4. AI-Generated Content", body:`Recipes and restaurant suggestions on Food Continent are generated by artificial intelligence. While we strive for accuracy:\n\n• We do not guarantee the accuracy, completeness, or safety of AI-generated recipes\n• Always use common sense and proper food safety practices when cooking\n• Check for allergens and dietary restrictions before consuming any recipe\n• We are not responsible for any adverse outcomes from following our recipes` },
          { title:"5. Third-Party Services", body:`Our Service integrates with third-party services including Google Places, Uber Eats, DoorDash, and GrubHub. We are not responsible for the content, accuracy, or practices of these third-party services. Your use of third-party services is governed by their respective terms of service.` },
          { title:"6. Advertising", body:`Food Continent displays advertisements provided by Google AdSense. We are not responsible for the content of these advertisements. By using our Service, you consent to the display of advertisements.` },
          { title:"7. Intellectual Property", body:`The Service and its original content, features, and functionality are owned by Food Continent and are protected by international copyright, trademark, and other intellectual property laws.` },
          { title:"8. Disclaimer of Warranties", body:`The Service is provided without any warranties, express or implied. We do not warrant that the Service will be uninterrupted, error-free, or free of viruses or other harmful components.` },
          { title:"9. Limitation of Liability", body:`Food Continent shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of or inability to use the Service.` },
          { title:"10. Changes to Terms", body:`We reserve the right to modify these terms at any time. We will notify users of significant changes by updating the "Last updated" date. Continued use of the Service after changes constitutes acceptance of the new terms.` },
          { title:"11. Contact", body:`For questions about these Terms, contact us at support@foodcontinent.com` },
        ].map((section, i) => (
          <div key={i} style={{ marginBottom:32 }}>
            <h2 style={{ fontSize:18, fontWeight:700, color:"#FF7A00", marginBottom:12 }}>{section.title}</h2>
            <p style={{ fontSize:14, color:"rgba(255,255,255,0.6)", lineHeight:1.8, whiteSpace:"pre-line" }}>{section.body}</p>
          </div>
        ))}

        <div style={{ textAlign:"center", marginTop:32, display:"flex", justifyContent:"center", gap:24 }}>
          <a href="/" style={{ color:"rgba(255,255,255,0.3)", fontSize:12, textDecoration:"none" }}>Home</a>
          <a href="/privacy" style={{ color:"rgba(255,255,255,0.3)", fontSize:12, textDecoration:"none" }}>Privacy Policy</a>
          <a href="/contact" style={{ color:"rgba(255,255,255,0.3)", fontSize:12, textDecoration:"none" }}>Contact</a>
        </div>
      </div>
    </div>
  );
}
